# Generated by cpp11: do not edit by hand

unigd_ugd_ <- function(bg, width, height, pointsize, aliases, reset_par) {
  .Call(`_unigd_unigd_ugd_`, bg, width, height, pointsize, aliases, reset_par)
}

unigd_state_ <- function(devnum) {
  .Call(`_unigd_unigd_state_`, devnum)
}

unigd_info_ <- function(devnum) {
  .Call(`_unigd_unigd_info_`, devnum)
}

unigd_renderers_ <- function() {
  .Call(`_unigd_unigd_renderers_`)
}

unigd_plot_find_ <- function(devnum, plot_id) {
  .Call(`_unigd_unigd_plot_find_`, devnum, plot_id)
}

unigd_render_ <- function(devnum, page, width, height, zoom, renderer_id) {
  .Call(`_unigd_unigd_render_`, devnum, page, width, height, zoom, renderer_id)
}

unigd_remove_ <- function(devnum, page) {
  .Call(`_unigd_unigd_remove_`, devnum, page)
}

unigd_remove_id_ <- function(devnum, plot_id) {
  .Call(`_unigd_unigd_remove_id_`, devnum, plot_id)
}

unigd_id_ <- function(devnum, page, limit) {
  .Call(`_unigd_unigd_id_`, devnum, page, limit)
}

unigd_clear_ <- function(devnum) {
  .Call(`_unigd_unigd_clear_`, devnum)
}

unigd_ipc_open_ <- function() {
  invisible(.Call(`_unigd_unigd_ipc_open_`))
}

unigd_ipc_close_ <- function() {
  invisible(.Call(`_unigd_unigd_ipc_close_`))
}
